config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "welcome#index"

  resources :foods
  resources :recipes do
    resources :recipe_foods, only: %i[new create edit update destroy]
    get '/recipe_shopping_list' => 'foods#recipe_shopping_list'
  end

  get '/public_recipes' => 'recipes#public'
  get '/general_shopping_list' => 'foods#general_shopping_list'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, :preparation_time, :cooking_time, :description, presence: true
  validates :preparation_time, :cooking_time, comparison: { greater_than_or_equal_to: 0 }

  def total_cost_calculator
    @total_cost = 0
    recipe_foods.each do |recipe_food|
      @total_cost += (recipe_food.quantity * recipe_food.food.price) / recipe_food.food.quantity
    end
    @total_cost
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: %i[show public] unless Rails.env == 'test'
  load_and_authorize_resource

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.where(user_id: current_user.id).includes(:user) unless Rails.env == 'test'
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @foods = if current_user.id == @recipe.user.id
               RecipeFood.where(recipe_id: @recipe.id).includes(:recipe, :food)
             else
               RecipeFood.where(recipe_id: @recipe.id).includes(:food)
             end
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_path, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def public
    @recipes = Recipe.includes(:user, recipe_foods: %i[food]).where(public: true).order(created_at: :desc)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipes = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description,
                                   :public).merge(user: current_user)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<div class="login" id="recipe-form">
  <div class="login-form">
    <h2>Recipe details</h2>

    <%= form_with(model: recipe) do |form| %>
      <% if recipe.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

          <ul>
            <% recipe.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name %>
      </div>

      <div>
        <%= form.label :preparation_time, style: "display: block" %>
        <%= form.number_field :preparation_time, min: 0, step: 0.5 %>
      </div>

      <div>
        <%= form.label :cooking_time, style: "display: block" %>
        <%= form.number_field :cooking_time, min: 0, step: 0.5 %>
      </div>

      <div>
        <%= form.label :description, style: "display: block" %>
        <%= form.text_area :description %>
      </div>

      <div>
        <%= form.check_box :public %>
        <%= form.label :public %>
      </div>

      <div>
        <%= form.submit %>
      </div>
    <% end %>
  </div>
  <div>
    <%= image_tag ("new.jpg") %>
  <div>
</div>

app/views/recipes/_public.html.erb
<div class="public_recipe" >
  <div class="recipe-left-section">
    <h3><%= recipe.name %></h3>
    <p>by <strong><%= recipe.user.name %></strong></p>
  </div>
  <div class="recipe-right-section">
    <p>Total food items: <%= recipe.foods.count%></p>
    <p>Total price: $ <%= recipe.total_cost_calculator %></p>
  </div>
  <div class="hidden_recipe_info">
    <p><%= recipe.description %></p>
    <%= link_to "See recipe", recipe_path(recipe), class: "see_recipe_btn" %>
  </div>
</div>
    

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class="recipe">
  <div>
    <%= image_tag ("recipe.jpg") %>
  </div>
  <div class="recipe-desc">
    <h2><%= recipe.name %></h2>
    <div class="recipe-links">
      <a href=<%= recipe_path(recipe) %> id="recipe-open">
        <i class="fa-solid fa-door-open"></i>
      </a>
      <% if can? :update, recipe %>
        <a href=<%= edit_recipe_path(recipe) %> id="recipe-edit">
          <i class="fa-solid fa-pen-to-square"></i>
        </a>
      <% end %>
      <% if can? :destroy, recipe %>
        <a href=<%= recipe_path(recipe) %> data-turbo-method="delete" id="recipe-delete">
          <i class="fa-solid fa-trash-can"></i>
        </a>
      <% end %>
    </div>
    <h5>Description</h5>
    <p><%= recipe.description %></p>
  </div>
</div>

app/views/recipes/edit.html.erb
<%= render "form", recipe: @recipe %>

app/views/recipes/index.html.erb
<div class="center">
  <button class="new-recipe">
    <%= link_to "New recipe", new_recipe_path %>
  </button>
</div>

<% if @recipes.length.zero? %> 
  <div class="empty">
    <%= image_tag ("empty.png") %>
    <h3>You don't have any recipes saved. Create a recipe to see it here</h3>
  </div>
<% else %>
  <div id="recipes">
    <% @recipes.each do |recipe| %>
      <%= render recipe %>
    <% end %>
  </div> 
<% end %>

app/views/recipes/new.html.erb
<%= render "form", recipe: @recipe %>

app/views/recipes/public.html.erb
<section class="public_section">
  <div class="public-recipes-holder">
  <h1 class="title">Public recipes</h1>
    <% if @recipes.empty? %>
      <p>There are no recipes to see, try again later.</p>
    <% else %>
      <% @recipes.each do |recipe| %>
          <%= render partial: 'public', locals: { recipe: } %>
      <% end %>
    <% end %>
  </div>
</section>

app/views/recipes/show.html.erb
<div class="recipe-show">
  <h2><%= @recipe.name %></h2>

  <div class="recipe-public">
    <h3>Preparation time: <%= @recipe.preparation_time %> hours</h3>
    <% if can? :update, @recipe %>
      <%= form_with(model: @recipe) do |form| %>
        <label class="switch">
          <%= form.label :public %>
          <%= form.check_box :public, onchange: 'this.form.submit();' %>
          <span class="slider round"></span>
        </label>
      <% end %>
    <% end %>
  </div>
  <h3>Cooking time: <%= @recipe.cooking_time %> hours</h3>
  <p> <%= @recipe.description %> </p>

  <div class="recipe-public">
    <button>
      <%= link_to "Generate shopping list", recipe_recipe_shopping_list_path(params[:id]) %> 
    </button>
    <% if can? :update, @recipe %>
      <button>
        <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe) %> 
      </button>
    <% end %>
  </div>

  <% if @foods.length.zero? %>
    <div class="empty">
      <%= image_tag ("empty.png") %>
      <h3>No ingredients added yet. Added ingredients will appear here</h3>
    </div>
  <% else %>
    <div id="foods">      
      <table>
          <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Value</th>
            <% if can? :update, @recipe %>
              <th>Actions</th>
            <% end %>
          </tr>
          <% @foods.each do |food| %>
            <tr>
              <td><%= food.food.name %></td>
              <td><%= food.quantity %></td>
              <td>$ <%= (food.quantity * food.food.price) / food.food.quantity %></td>
              <% if can? :update, @recipe %>
                <td>
                  <div class="food-actions">
                    <a href=<%= edit_recipe_recipe_food_path(recipe_id: params[:id], id: food.id) %> id="food-edit">
                  <i class="fa-regular fa-pen-to-square"></i> 
                </a>
                    <a href=<%= recipe_recipe_food_path(food.recipe.id, food.id) %> data-turbo-method="delete" id="food-delete">
                      <i class="fa-solid fa-trash-can"></i>
                    </a>
                  </div>
                </td>
              <% end %>
            </tr>
          <% end %>
        </table>
      </div>
  <% end %>
</div>