config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "welcome#index"

  resources :foods
  resources :recipes do
    resources :recipe_foods, only: %i[new create edit update destroy]
    get '/recipe_shopping_list' => 'foods#recipe_shopping_list'
  end

  get '/public_recipes' => 'recipes#public'
  get '/general_shopping_list' => 'foods#general_shopping_list'
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, :measurement_unit, :price, :quantity, presence: true
  validates :price, :quantity, comparison: { greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user! unless Rails.env == 'test'
  load_and_authorize_resource

  # GET /foods or /foods.json
  def index
    @current_user = current_user
    @foods = Food.where(user_id: current_user)
  end

  # GET /foods/new
  def new
    @current_user = current_user
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params.merge(user: current_user))

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully added.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to foods_path, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully removed.' }
      format.json { head :no_content }
    end
  end

  def general_shopping_list
    @all_foods = Food.all
    @recipes = Recipe.includes(recipe_foods: [:food]).where(user: current_user)
    @foods = {}
    @total_cost = 0
    @food_count = 0
    @recipes.each do |recipe|
      recipe.recipe_foods.each do |recipe_food|
        name = recipe_food.food.name
        if @foods[name]
          @foods[name] += recipe_food.quantity
        else
          @food_count += 1
          @foods[name] = recipe_food.quantity
        end
      end
      @total_cost += recipe.total_cost_calculator
    end
  end

  def recipe_shopping_list
    @recipe = Recipe.includes(recipe_foods: %i[food]).find_by(id: params[:recipe_id])
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :quantity, :price)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>User:</strong>
    <%= food.user_id %>
  </p>

</div>

app/views/foods/_form.html.erb
<div class="food-form">
  <%= form_with(model: food) do |form| %>
    <% if food.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>
  
        <ul>
          <% food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name, placeholder: 'Name here..' %>
    </div>
  
    <div>
      <%= form.label :measurement_unit, style: "display: block" %>
      <%= form.text_field :measurement_unit, placeholder: 'Ex: grams, liters..' %>
    </div>
  
    <div>
      <%= form.label :quantity, style: "display: block" %>
      <%= form.text_field :quantity, placeholder: 'Quantity..' %>
    </div>
  
    <div>
      <%= form.label :price, style: "display: block" %>
      <%= form.text_field :price, placeholder: 'In USD' %>
    </div>
  
    <div id='create_food_btn'>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/foods/edit.html.erb
<div class="food-form-wrapper">
  <h1>Editing food</h1>
  
  <%= render "form", food: @food %>
  
  <br>
  
  <div>
    <a href= <%= foods_path %> class="back-button">
      <span class="back-icon"></span>
      <span class="back-text"><i class="fa-solid fa-utensils foods-btn"></i></span>
    </a>
  </div>
</div>

app/views/foods/general_shopping_list.html.erb
<div class="shopping-wrapper">
  <h2>General shopping List:</h2>
  <div class="shopping-info">
    <p>Amount of food items to buy: <strong><%= @food_count %></strong></p>
    <p>Total value of food needed: $ <strong><%= @total_cost %></strong></p>
  </div>
  <% if @foods.empty? %>
    <p class="no-foods-msg"><%= image_tag ("no-content.png"), id: 'no-content-img' %>There are no foods added in recipes.</p>
  <% else %>
    <div id="foods">
      <table>
          <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Price</th>
          </tr>
          <% @all_foods.each do |food| %>
            <tr>
              <% if @foods[food.name] %>
                <td><%= food.name %></td>
                <td><%= @foods[food.name] %> <span id="unit"><%= food.measurement_unit %></span></td>
                <td>$ <%= (@foods[food.name] * food.price) / food.quantity %></td>
              <% end %>
          </tr>
        <% end %>
      </table>
      </div>
  <% end %>
</div>

app/views/foods/index.html.erb
<div class="foods-wrapper">
  
  <% if @current_user %>
    <%= link_to "Add Food", new_food_path, id: "add_food_btn" %>
  <% end %>
  
  
  <% if @foods.empty? %>
    <p class="no-foods-msg"><%= image_tag ("no-content.png"), id: 'no-content-img' %>There are no foods added currently</p>
  <% else %>
  <h1>Foods:</h1>
    <div id="foods">
    <table>
        <tr>
          <th>Food</th>
          <th>Measurement Unit</th>
          <th>Quantity</th>
          <th>Price</th>
          <th>Action</th>
        </tr>
        <% @foods.each do |food| %>
          <tr>
            <td><%= food.name %></td>
            <td><%= food.measurement_unit %></td>
            <td><%= food.quantity %></td>
            <td>$ <%= food.price %></td>
            <td>
              <div class="food-actions">
                <a href=<%= edit_food_path(food) %> id="food-edit">
                  <i class="fa-regular fa-pen-to-square"></i> 
                </a>
                <a href=<%= food_path(food) %> data-turbo-method="delete" id="food-delete">
                  <i class="fa-solid fa-trash-can"></i>
                </a>
              </div>
            </td>
        </tr>
      <% end %>
    </table>
    </div>
  <% end %>
</div>

app/views/foods/new.html.erb
<div class="food-form-wrapper">
  <h1>New food</h1>
  
  <%= render "form", food: @food %>
  
  <br>
  
  <div>
    <a href= <%= foods_path %> class="back-button">
      <span class="back-icon"></span>
      <span class="back-text">Back</span>
    </a>
  </div>
</div>

app/views/foods/recipe_shopping_list.html.erb
<div class="shopping-wrapper">
  <h2>Recipe shopping List:</h2>
  <div class="shopping-info">
    <p>Amount of food items to buy: <strong><%= @recipe.recipe_foods.count %></strong></p>
    <p>Total value of food needed: $ <strong><%= @recipe.total_cost_calculator %></strong></p>
  </div>

  <% if @recipe.recipe_foods.empty? %>
    <p class="no-foods-msg"><%= image_tag ("no-content.png"), id: 'no-content-img' %>There are no foods added for this recipe.</p>
  <% else %>
    <div id="foods">
      <table>
          <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Price</th>
          </tr>
          <% @recipe.recipe_foods.each do |recipe_food| %>
            <tr>
              <td><%= recipe_food.food.name %></td>
              <td><%= recipe_food.quantity %> <span id="unit"><%= recipe_food.food.measurement_unit %></span></td>
              <td>$ <%= (recipe_food.quantity * recipe_food.food.price) / recipe_food.food.quantity %></td>
          </tr>
        <% end %>
      </table>
      </div>
  <% end %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>