config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "welcome#index"

  resources :foods
  resources :recipes do
    resources :recipe_foods, only: %i[new create edit update destroy]
    get '/recipe_shopping_list' => 'foods#recipe_shopping_list'
  end

  get '/public_recipes' => 'recipes#public'
  get '/general_shopping_list' => 'foods#general_shopping_list'
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!
  # load_and_authorize_resource

  def new
    @recipe_food = RecipeFood.new
    @foods = []
    @ids = RecipeFood.where(recipe_id: params[:recipe_id]).pluck(:food_id)
    Food.where(user: current_user).each do |f|
      @foods << [f.name, f.id] unless @ids.include?(f.id)
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe_food = RecipeFood.includes(:food).find_by(id: params[:id])
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new(recipe_food_params)

    respond_to do |format|
      if @recipe_food.save
        format.html { redirect_to recipe_path(@recipe), notice: 'Ingredient was successfully added.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    @recipe_food = RecipeFood.find_by(id: params[:id])
    respond_to do |format|
      if @recipe_food.update(recipe_food_params)
        format.html { redirect_to recipe_url(params[:recipe_id]), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy

    respond_to do |format|
      format.html { redirect_to recipe_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipes = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id).merge(recipe: Recipe.find(params[:recipe_id]))
  end
end

app/views/recipe_foods/edit.html.erb
<div class="foods-wrapper">
  <h3>Edit recipe food:</h3>
              <%= form_with(model: @recipe_food, url: recipe_recipe_food_path, method: :put) do |form| %>
  <table>
            <tr>
              <th>Food</th>
              <th>Quantity</th>
              <th>Actions</th>
            </tr>
            <tr>
              <td><%= @recipe_food.food.name %></td>
              <td>
              <%= form.number_field :quantity, value: @recipe_food.quantity %>
              </td>
              <td>
                <div class="food-actions">
                <%= form.submit id: 'update-recipe_food-btn' %>
                </div>
              </td>
              </tr>
          </table>
          <% end %>
</div>
<%= @recipe_food.quantity %>

app/views/recipe_foods/new.html.erb
<div class="login" id="recipe-form">
  <div class="login-form">  
    <%= form_with(model: @recipe_food, url: recipe_recipe_foods_path) do |form| %>
      <% if @recipe_food.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(@recipe_food.errors.count, "error") %> prohibited this food from being saved:</h2>
    
          <ul>
            <% @recipe_food.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.select :food_id, @foods, { :include_blank => '-- Select One --' }, :required => true %>
      </div>
    
      <div>
        <%= form.label :quantity, style: "display: block" %>
        <%= form.number_field :quantity, placeholder: 'Quantity..', :required => true %>
      </div>
    
      <div>
        <%= form.submit "Add ingredient" %>
      </div>
    <% end %>
  </div>
  <div>
    <%= image_tag ("food.jpg") %>
  <div>
</div>