config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "welcome#index"

  resources :foods
  resources :recipes do
    resources :recipe_foods, only: %i[new create edit update destroy]
    get '/recipe_shopping_list' => 'foods#recipe_shopping_list'
  end

  get '/public_recipes' => 'recipes#public'
  get '/general_shopping_list' => 'foods#general_shopping_list'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.png') %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
  </head>

  <body>
    <% if user_signed_in? && request.env['PATH_INFO'] != root_path %>
      <header>
        <ul>
          <li>
            <%= link_to "Public Recipes", public_recipes_path %>
          </li>
          <li>
            <%= link_to "Foods", foods_path %>
          </li>
          <li>
            <%= link_to "Recipes", recipes_path %>
          </li>
           <li>
            <%= link_to "Shopping List", general_shopping_list_path %>
          </li>
        </ul>
      </header>
    <% end %>

    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <% if user_signed_in? && request.env['PATH_INFO'] != root_path %>
      <div class="welcome">
        <h1>Hello <%= current_user.name %></h1>
        <%= button_to "Logout", destroy_user_session_path, method: :delete %> 
      </div>
    <% end %>

    <%= yield %>
    <% if request.env['PATH_INFO'] != root_path %>
      <footer>Copyright &copy 2023 All rights reserved. Created by <a href="https://github.com/Shisui6" class="profile-link">Okemdi Udeh</a> & 
        <a href="https://github.com/yonas44" class="profile-link">Yonas Tesfu</a></footer>
    <% end %>
  </body>
</html>